apiVersion: v1
kind: PersistentVolume
metadata:
  name: t1database-t1
  labels:
    ht.storage.name: t1database-t1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - vers=4.0
  nfs:
    path: /testing1-2-3/databases/t1
    server: *.*.nas.aliyuncs.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t1database
  namespace: default
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      ht.storage.name: t1database-t1
