apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  #stubDomains: |
  #  {"bj.hetao101.com": ["10.100.5.1"],"corp.hetao101.com":["10.100.5.1"]}
  upstreamNameservers: |
    ["114.114.114.114","8.8.8.8"]
